package com.codearchive.api.community;

import static org.assertj.core.api.Assertions.*;
import com.codearchive.api.solution.Platform;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class CommunityStoreSchemaTest {
    @Test void productionSchemaCannotReadOrWriteLegacyPublicTables() {
        var source = new DriverManagerDataSource("jdbc:h2:mem:community-schema;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1", "sa", "");
        var db = new JdbcTemplate(source);
        db.execute("create schema codearchive_v2");
        String table = "solutions(id bigint, user_id bigint, platform varchar(20), problem_number varchar(100), result varchar(20), published_at timestamp)";
        db.execute("create table public." + table);
        db.execute("create table codearchive_v2." + table);
        db.update("insert into public.solutions values(1, 7, 'SWEA', '1234', 'ACCEPTED', CURRENT_TIMESTAMP)");
        var store = new CommunityStore(new NamedParameterJdbcTemplate(db), "codearchive_v2");
        assertThatThrownBy(() -> store.requireEligibility(7, Platform.SWEA, "1234")).isInstanceOf(CommunityService.NotEligibleException.class);
        assertThatThrownBy(() -> store.requireAccess(7, 1)).isInstanceOf(java.util.NoSuchElementException.class);
        db.update("insert into codearchive_v2.solutions values(1, 7, 'SWEA', '1234', 'ACCEPTED', CURRENT_TIMESTAMP)");
        assertThatCode(() -> store.requireEligibility(7, Platform.SWEA, "1234")).doesNotThrowAnyException();
        assertThatCode(() -> store.requireAccess(7, 1)).doesNotThrowAnyException();
        db.execute("create table codearchive_v2.community_likes(id bigint generated by default as identity, solution_id bigint, user_id bigint)");
        db.execute("create table codearchive_v2.community_comments(id bigint generated by default as identity, solution_id bigint, user_id bigint, body varchar(2000), created_at timestamp, updated_at timestamp)");
        assertThat(store.like(7, 1, true).likeCount()).isEqualTo(1);
        store.comment(7, 1, null, "schema fixture", false);
        assertThat(db.queryForObject("select count(*) from codearchive_v2.community_comments", Long.class)).isEqualTo(1);
        assertThat(db.queryForObject("select count(*) from public.solutions", Long.class)).isEqualTo(1);
    }
}
