package com.codearchive.api.automation;
import com.codearchive.api.auth.AppUser; import com.codearchive.api.settings.*; import com.codearchive.api.solution.*; import java.time.*; import java.util.*; import java.util.function.Supplier; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.beans.factory.annotation.Value; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.transaction.PlatformTransactionManager; import org.springframework.transaction.support.TransactionTemplate;
@Service public class GithubAutomationService {
 private final GithubCommitJobRepository jobs; private final UserSettingsRepository settings; private final SolutionRepository solutions; private final GithubProvider provider; private final TransactionTemplate transactions; private final Duration runningLease;
 @Autowired public GithubAutomationService(GithubCommitJobRepository jobs,UserSettingsRepository settings,SolutionRepository solutions,GithubProvider provider,PlatformTransactionManager manager,@Value("${codearchive.github.worker-running-lease-ms:300000}") long runningLeaseMs){this.jobs=jobs;this.settings=settings;this.solutions=solutions;this.provider=provider;this.transactions=new TransactionTemplate(manager);this.runningLease=Duration.ofMillis(Math.max(1000,runningLeaseMs));}
 /** Test-only compatibility constructor; production always receives a transaction manager. */ public GithubAutomationService(GithubCommitJobRepository jobs,UserSettingsRepository settings,SolutionRepository solutions,GithubProvider provider){this.jobs=jobs;this.settings=settings;this.solutions=solutions;this.provider=provider;this.transactions=null;this.runningLease=Duration.ofMinutes(5);}
 @Transactional public void consider(AppUser user,Solution solution){ UserSettings s=settings.findByUserId(user.getId()).orElse(null); if(s==null||!s.isAutoSyncEnabled()||!s.isGithubAutoCommitEnabled()||!s.githubTargetConfigured()||s.getAutomationEnabledAt()==null||solution.getObservedAt().isBefore(s.getAutomationEnabledAt()))return; jobs.findByUserIdAndCaptureId(user.getId(),solution.getCaptureId()).orElseGet(()->jobs.save(new GithubCommitJob(user,solution.getCaptureId(),s.getVersion()))); }
 @Scheduled(fixedDelayString="${codearchive.github.worker-delay-ms:30000}") public void poll(){
   // A fresh RUNNING lease can belong to another worker. Only an abandoned
   // lease is made UNKNOWN; it is never reclaimed automatically.
   Instant staleBefore=Instant.now().minus(runningLease);
   inTransaction(()->{jobs.findTop25ByStateAndUpdatedAtBeforeOrderByCreatedAtAsc(CommitJobState.RUNNING,staleBefore).forEach(job->{job.terminal(CommitJobState.UNKNOWN);jobs.saveAndFlush(job);});return null;});
   List<Long> pending=inTransaction(()->jobs.findTop25ByStateOrderByCreatedAtAsc(CommitJobState.PENDING).stream().map(GithubCommitJob::getId).toList()); pending.forEach(this::process);
 }
 public void process(Long id){ Claim claim=inTransaction(()->claim(id)); if(claim==null)return; GithubProvider.Result result; try{result=provider.createOnly(claim.settings(),claim.solution(),()->finalWriteAuthorized(claim));}catch(RuntimeException ex){result=GithubProvider.Result.unknown("Provider threw after durable claim");} final GithubProvider.Result outcome=result; inTransaction(()->{GithubCommitJob job=jobs.findById(id).orElse(null);if(job==null||job.getState()!=CommitJobState.RUNNING)return null;switch(outcome.outcome()){case SUCCEEDED->job.terminal(CommitJobState.SUCCEEDED);case UNKNOWN->job.terminal(CommitJobState.UNKNOWN);case FAILED->job.terminal(CommitJobState.FAILED);case RETRYABLE->{if(job.getAttempts()>=3)job.terminal(CommitJobState.FAILED);else job.retry();}}jobs.saveAndFlush(job);return null;}); }
 private Claim claim(Long id){GithubCommitJob job=jobs.findByIdForClaim(id).orElse(null);if(job==null||job.getState()!=CommitJobState.PENDING)return null;UserSettings s=settings.findByUserId(job.getUser().getId()).orElse(null);Solution solution=solutions.findByUserIdAndCaptureId(job.getUser().getId(),job.getCaptureId()).orElse(null);if(s==null||solution==null||!s.isAutoSyncEnabled()||!s.isGithubAutoCommitEnabled()||!s.githubTargetConfigured()||s.getVersion()!=job.getSettingsGeneration()){job.terminal(CommitJobState.FAILED);jobs.saveAndFlush(job);return null;}job.start();jobs.saveAndFlush(job);return new Claim(s,solution);}
 private boolean finalWriteAuthorized(Claim claim){UserSettings current=settings.findByUserId(claim.settings().getUser().getId()).orElse(null);return current!=null&&current.getVersion()==claim.settings().getVersion()&&current.isAutoSyncEnabled()&&current.isGithubAutoCommitEnabled()&&current.githubTargetConfigured();}
 private <T>T inTransaction(Supplier<T> work){if(transactions==null)return work.get();return transactions.execute(status->work.get());} private record Claim(UserSettings settings,Solution solution){}
}
