import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { parseHTML } from 'linkedom';
import { mountDesktopConnection } from '../src/popupDesktopView';
const html = readFileSync(new URL('../src/popup.html', import.meta.url), 'utf8');
const settle = () => new Promise(resolve => setImmediate(resolve));
test('popup gates actions on connection, hides pairing when connected, and returns on disconnect', async () => {
  const { document } = parseHTML(html);
  let connected = false;
  const view = mountDesktopConnection(document, { send: async () => ({ connected }), schedule: () => {} });
  await settle();
  assert.equal(document.querySelector<HTMLElement>('#popup-content')!.hidden, true);
  assert.equal(document.querySelector<HTMLElement>('#desktop-entry')!.hidden, false);
  assert.equal(document.querySelector('#desktop-entry .dashboard-link')?.getAttribute('href'), 'codearchive://app/open');
  connected = true; await view.refresh();
  assert.equal(document.querySelector<HTMLElement>('#popup-content')!.hidden, false);
  assert.equal(document.querySelector<HTMLElement>('#desktop-entry')!.hidden, true);
  assert.equal(document.querySelector('#capture-card .dashboard-link')?.getAttribute('href'), 'codearchive://app/open');
  connected = false; await view.refresh();
  assert.equal(document.querySelector<HTMLElement>('#popup-content')!.hidden, true);
  assert.equal(document.querySelector('#extension-update-check'), null);
});
test('connection lookup failure keeps actions hidden and permits a later successful refresh', async () => {
  const { document } = parseHTML(html);
  let fail = true;
  const view = mountDesktopConnection(document, { send: async () => { if (fail) throw Error('offline'); return { connected: true }; }, schedule: () => {} });
  await settle();
  assert.equal(document.querySelector<HTMLElement>('#popup-content')!.hidden, true);
  assert.match(document.querySelector('#desktop-status')!.textContent!, /확인하지 못했습니다/);
  fail = false; await view.refresh();
  assert.equal(document.querySelector<HTMLElement>('#desktop-entry')!.hidden, true);
});
