spring:
  datasource:
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: codearchive_v2
  flyway:
    schemas: codearchive_v2
    default-schema: codearchive_v2
    create-schemas: true

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
