// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { vi, describe, it, expect, beforeEach, afterEach } from 'vitest'
import { SupportView } from './SupportView'

const mocks = vi.hoisted(() => ({ access: vi.fn(), list: vi.fn(), adminList: vi.fn(), detail: vi.fn(), adminDetail: vi.fn(), create: vi.fn(), me: vi.fn(), reply: vi.fn(), adminReply: vi.fn(), status: vi.fn(), remove: vi.fn() }))
const ApiMockError = vi.hoisted(() => class ApiError extends Error { constructor(message = 'error', readonly status = 500) { super(message) } })
vi.mock('./api', () => ({ ApiError: ApiMockError, getSupportAccess: mocks.access, getSupportTickets: mocks.list, getSupportAdminTickets: mocks.adminList, getSupportTicket: mocks.detail, getSupportAdminTicket: mocks.adminDetail, createSupportTicket: mocks.create, getMe: mocks.me, replySupportTicket: mocks.reply, replySupportAdminTicket: mocks.adminReply, setSupportAdminStatus: mocks.status, closeSupportTicket: mocks.status, deleteSupportTicket: mocks.remove }))
const user = { id: 1, githubId: '42', githubLogin: 'tester' }
const summary = { id: 7, category: 'BUG' as const, title: 'ticket', status: 'OPEN' as const, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z', closedAt: null }
const ticket = { inquiry: summary, messages: [{ id: 1, authorRole: 'USER' as const, body: 'body', createdAt: '2026-01-01T00:00:00Z' }], admin: false }
describe('SupportView', () => {
  afterEach(cleanup)
  beforeEach(() => { vi.clearAllMocks(); mocks.access.mockResolvedValue({ admin: false, closedRetentionDays: 90 }); mocks.list.mockResolvedValue({ items: [], page: 0, size: 20, total: 0, hasMore: false }); mocks.adminList.mockResolvedValue({ items: [], page: 0, size: 20, total: 0, hasMore: false }); mocks.me.mockResolvedValue(user) })
  it('shows a login-needed state without an account and does not load private tickets', () => { render(<SupportView user={null} mode="local" onLogin={vi.fn()} onAuthInvalid={vi.fn()} />); expect(screen.getByText('GitHub로 로그인')).toBeTruthy(); expect(mocks.list).not.toHaveBeenCalled() })
  it('validates and submits a private inquiry for the current account', async () => { mocks.create.mockResolvedValue({ inquiry: { id: 1, category: 'BUG', title: 'title', status: 'OPEN', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z', closedAt: null }, messages: [], admin: false }); render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={vi.fn()} />); await waitFor(() => expect(mocks.list).toHaveBeenCalledWith('42', 0)); fireEvent.change(screen.getByLabelText('제목'), { target: { value: 'title' } }); fireEvent.change(screen.getByLabelText('내용'), { target: { value: 'body' } }); fireEvent.click(screen.getByText('문의 등록')); await waitFor(() => expect(mocks.create).toHaveBeenCalledWith('42', { category: 'BUG', title: 'title', body: 'body' })) })
  it('fences an account-switched read before private data can render', async () => { let release!: (value: { admin: boolean; closedRetentionDays: number }) => void; mocks.access.mockImplementationOnce(() => new Promise(resolve => { release = resolve })).mockResolvedValueOnce({ admin: false, closedRetentionDays: 90 }); const view = render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={vi.fn()} />); view.rerender(<SupportView user={{ ...user, githubId: '43' }} mode="live" onLogin={vi.fn()} onAuthInvalid={vi.fn()} />); release({ admin: false, closedRetentionDays: 90 }); await waitFor(() => expect(mocks.list).toHaveBeenCalledWith('43', 0)); expect(mocks.list).not.toHaveBeenCalledWith('42', 0) })
  it('clears current private state and invalidates authentication on a 401 read', async () => { const invalid = vi.fn(); mocks.access.mockRejectedValueOnce(new ApiMockError('expired', 401)); render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={invalid} />); await waitFor(() => expect(invalid).toHaveBeenCalledTimes(1)); expect(mocks.list).not.toHaveBeenCalled() })
  it('clears preloaded detail and drafts on a current 409 write check', async () => { const invalid = vi.fn(); mocks.list.mockResolvedValue({ items: [summary], page: 0, size: 20, total: 1, hasMore: false }); mocks.detail.mockResolvedValue(ticket); render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={invalid} />); await waitFor(() => screen.getByText('ticket')); fireEvent.click(screen.getByText('ticket')); await waitFor(() => screen.getByLabelText('문의 답변')); fireEvent.change(screen.getByLabelText('문의 답변'), { target: { value: 'draft' } }); mocks.me.mockRejectedValueOnce(new ApiMockError('changed', 409)); fireEvent.click(screen.getByText('답변 보내기')); await waitFor(() => expect(invalid).toHaveBeenCalledTimes(1)); expect(screen.queryByLabelText('문의 답변')).toBeNull(); expect((screen.getByLabelText('제목') as HTMLInputElement).value).toBe('') })
  it('loads the next bounded ticket page', async () => { mocks.list.mockResolvedValue({ items: [], page: 0, size: 20, total: 21, hasMore: true }); render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={vi.fn()} />); await waitFor(() => expect(mocks.list).toHaveBeenCalledWith('42', 0)); const next = screen.getAllByText('다음').filter(button => !(button as HTMLButtonElement).disabled); fireEvent.click(next[next.length - 1]); await waitFor(() => expect(mocks.list).toHaveBeenCalledWith('42', 1)) })
  it('only loads administrator tickets after verified access', async () => { mocks.access.mockResolvedValue({ admin: true, closedRetentionDays: 90 }); render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={vi.fn()} />); await waitFor(() => expect(screen.getByText('전체 문의 관리자 보기')).toBeTruthy()); fireEvent.click(screen.getByText('전체 문의 관리자 보기')); await waitFor(() => expect(mocks.adminList).toHaveBeenCalledWith('42', 0)) })
  it('admin can reply and close a verified ticket', async () => { mocks.access.mockResolvedValue({ admin: true, closedRetentionDays: 90 }); mocks.adminList.mockResolvedValue({ items: [summary], page: 0, size: 20, total: 1, hasMore: false }); mocks.adminDetail.mockResolvedValue({ ...ticket, admin: true }); mocks.adminReply.mockResolvedValue({ ...ticket, admin: true }); mocks.status.mockResolvedValue({ ...ticket, inquiry: { ...summary, status: 'CLOSED' }, admin: true }); render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={vi.fn()} />); await waitFor(() => screen.getByText('전체 문의 관리자 보기')); fireEvent.click(screen.getByText('전체 문의 관리자 보기')); await waitFor(() => screen.getByText('ticket')); fireEvent.click(screen.getByText('ticket')); await waitFor(() => screen.getByLabelText('문의 답변')); fireEvent.change(screen.getByLabelText('문의 답변'), { target: { value: 'answer' } }); fireEvent.click(screen.getByText('답변 보내기')); await waitFor(() => expect(mocks.adminReply).toHaveBeenCalledWith('42', 7, 'answer')); fireEvent.click(screen.getByText('문의 종료')); await waitFor(() => expect(mocks.status).toHaveBeenCalledWith('42', 7, 'CLOSED')) })
  it('requires confirmation before owner deletion', async () => { vi.stubGlobal('confirm', vi.fn(() => true)); mocks.list.mockResolvedValue({ items: [summary], page: 0, size: 20, total: 1, hasMore: false }); mocks.detail.mockResolvedValue(ticket); mocks.remove.mockResolvedValue(undefined); render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={vi.fn()} />); await waitFor(() => screen.getByText('ticket')); fireEvent.click(screen.getByText('ticket')); await waitFor(() => screen.getByText('문의 삭제')); fireEvent.click(screen.getByText('문의 삭제')); await waitFor(() => expect(mocks.remove).toHaveBeenCalledWith('42', 7)); vi.unstubAllGlobals() })
  it('keeps the composer empty when a pending detail resolves after 새 문의', async () => { let release!: (value: typeof ticket) => void; mocks.list.mockResolvedValue({ items: [summary], page: 0, size: 20, total: 1, hasMore: false }); mocks.detail.mockReset().mockImplementation(() => new Promise(resolve => { release = resolve })); render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={vi.fn()} />); await waitFor(() => screen.getByText('ticket')); fireEvent.click(screen.getByText('ticket')); await waitFor(() => expect(mocks.detail).toHaveBeenCalledWith('42', 7)); await waitFor(() => expect(release).toBeTypeOf('function')); fireEvent.click(screen.getByRole('button', { name: '새 문의' })); release(ticket); await waitFor(() => expect(screen.getByText('문의 등록')).toBeTruthy()); expect(screen.queryByLabelText('문의 답변')).toBeNull() })
  it('does not dispatch a pending write after account switching before getMe', async () => { let release!: (value: typeof user) => void; mocks.me.mockImplementationOnce(() => new Promise(resolve => { release = resolve })); const invalid = vi.fn(); const view = render(<SupportView user={user} mode="live" onLogin={vi.fn()} onAuthInvalid={invalid} />); await waitFor(() => screen.getByLabelText('제목')); fireEvent.change(screen.getByLabelText('제목'), { target: { value: 'title' } }); fireEvent.change(screen.getByLabelText('내용'), { target: { value: 'body' } }); fireEvent.click(screen.getByText('문의 등록')); view.rerender(<SupportView user={{ ...user, githubId: '43' }} mode="live" onLogin={vi.fn()} onAuthInvalid={invalid} />); release(user); await waitFor(() => expect(mocks.create).not.toHaveBeenCalled()); expect(invalid).not.toHaveBeenCalled() })
})
