CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE solutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    capture_id VARCHAR(36) NOT NULL,
    platform VARCHAR(20) NOT NULL,
    problem_number VARCHAR(100) NOT NULL,
    title VARCHAR(500) NOT NULL,
    problem_url VARCHAR(2048) NOT NULL,
    language VARCHAR(100) NOT NULL,
    source_code TEXT NOT NULL,
    result VARCHAR(20) NOT NULL,
    observed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    solved_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    execution_time NUMERIC(19, 6),
    memory_usage NUMERIC(19, 6),
    CONSTRAINT pk_solutions PRIMARY KEY (id),
    CONSTRAINT uk_solution_user_capture UNIQUE (user_id, capture_id),
    CONSTRAINT fk_solution_user FOREIGN KEY (user_id) REFERENCES users (id)
);
