CREATE TABLE support_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category VARCHAR(20) NOT NULL,
    title VARCHAR(150) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_support_inquiries_category CHECK (category IN ('BUG', 'QUESTION', 'DATA_REQUEST')),
    CONSTRAINT ck_support_inquiries_status CHECK (status IN ('OPEN', 'ANSWERED', 'CLOSED'))
);
CREATE INDEX idx_support_inquiries_owner_created ON support_inquiries(owner_id, created_at DESC, id DESC);
CREATE INDEX idx_support_inquiries_closed_at ON support_inquiries(closed_at);

CREATE TABLE support_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id BIGINT NOT NULL REFERENCES support_inquiries(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    author_role VARCHAR(10) NOT NULL,
    body VARCHAR(10000) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_support_messages_author_role CHECK (author_role IN ('USER', 'ADMIN'))
);
CREATE INDEX idx_support_messages_inquiry ON support_messages(inquiry_id, id ASC);
