const test = require('node:test');
const assert = require('node:assert/strict');
const { once } = require('node:events');
const { createHmac } = require('node:crypto');
const { WebSocket } = require('ws');
const http = require('node:http');
const { createExtensionServer } = require('../src/extension-server.cjs');
const { EXTENSION_ID, apiRequest, authUrl, externalUrl, trustedRenderer } = require('../src/policy.cjs');
const origin = `chrome-extension://${EXTENSION_ID}`;
test('loopback pairing rejects web origins, expires, limits guesses and consumes a valid code once', async t => {
  let now = 1000, token;
  const server = createExtensionServer({ port: 0, now: () => now, saveToken: async value => { token = value; } });
  const port = await server.listen(); t.after(() => server.close());
  const pair = (code, caller = origin) => fetch(`http://127.0.0.1:${port}/pair`, { method: 'POST', headers: { Origin: caller, 'Content-Type': 'application/json' }, body: JSON.stringify({ code }) });
  const first = server.createPairCode();
  assert.equal((await pair(first.code, 'https://evil.test')).status, 403);
  now += 120001; assert.equal((await pair(first.code)).status, 403);
  const second = server.createPairCode();
  for (let i = 0; i < 5; i++) assert.equal((await pair('wrong')).status, 403);
  assert.equal((await pair(second.code)).status, 403);
  const final = server.createPairCode();
  const response = await pair(final.code); assert.equal(response.status, 200);
  assert.equal((await response.json()).token, token); assert.match(token, /^[a-f0-9]{64}$/);
  assert.equal((await pair(final.code)).status, 403);
});
test('authenticated WebSocket transports requests; disconnect and revocation invalidate the connection', async t => {
  const token = 'a'.repeat(64);
  const server = createExtensionServer({ port: 0, token, saveToken: async () => {} });
  const port = await server.listen(); t.after(() => server.close());
  const wrong = new WebSocket(`ws://127.0.0.1:${port}/bridge`, { origin });
  const wrongChallenge = once(wrong, 'message');
  await once(wrong, 'open'); wrong.send(JSON.stringify({ type: 'HELLO', nonce: 'c'.repeat(64) })); await wrongChallenge; wrong.send(JSON.stringify({ type: 'AUTH', proof: 'b'.repeat(64) })); await once(wrong, 'close');
  assert.equal(server.connected(), false);
  const client = new WebSocket(`ws://127.0.0.1:${port}/bridge`, { origin });
  const challengeResponse = once(client, 'message');
  await once(client, 'open');
  client.send(JSON.stringify({ type: 'HELLO', nonce: 'd'.repeat(64) }));
  const challenge = JSON.parse((await challengeResponse)[0]);
  assert.equal(challenge.clientNonce, 'd'.repeat(64));
  assert.equal(challenge.proof, createHmac('sha256', token).update(`server:${challenge.clientNonce}:${challenge.nonce}`).digest('hex'));
  const ready = once(client, 'message'); client.send(JSON.stringify({ type: 'AUTH', proof: createHmac('sha256', token).update(`client:${challenge.clientNonce}:${challenge.nonce}`).digest('hex') }));
  const confirmation = JSON.parse((await ready)[0]);
  assert.equal(confirmation.type, 'READY'); assert.equal(confirmation.proof, createHmac('sha256', token).update(`ready:${challenge.clientNonce}:${challenge.nonce}`).digest('hex')); assert.equal(server.connected(), true);
  client.on('message', data => { const value = JSON.parse(data); if (value.type === 'REQUEST') client.send(JSON.stringify({ type: 'RESPONSE', id: value.id, response: { pendingCount: 3 } })); });
  assert.deepEqual(await server.request({ type: 'GET_STATUS' }), { pendingCount: 3 });
  const closed = once(client, 'close'); await server.disconnect(); await closed;
  await assert.rejects(server.request({ type: 'CONNECT' }));
});
test('API proxy and IPC policies do not admit arbitrary URLs, credentials, frames or headers', () => {
  assert.equal(apiRequest({ path: '/api/auth/me' }).url, 'https://codearchive-dashboard-beta.netlify.app/api/auth/me');
  for (const path of ['https://evil.test/api/foo', '//evil.test/api/foo', '/api/../../secret', '/api/\\evil.test', '/api/auth/me#oops']) assert.throws(() => apiRequest({ path }));
  assert.throws(() => apiRequest({ path: '/api/auth/me', headers: { Authorization: 'arbitrary' } }));
  assert.throws(() => authUrl('https://evil.test'));
  assert.throws(() => externalUrl('file:///C:/Windows'));
  const mainFrame = { url: 'codearchive://app/index.html?view=settings' };
  assert.equal(trustedRenderer(mainFrame, { mainFrame }), true);
  assert.equal(trustedRenderer({ ...mainFrame }, { mainFrame }), false);
  mainFrame.url = 'https://github.com'; assert.equal(trustedRenderer(mainFrame, { mainFrame }), false);
});
test('pairing rechecks expiry, failed attempts and generation after a delayed request body', { timeout: 5000 }, async t => {
  let now = 1000, admitted;
  const server = createExtensionServer({ port: 0, now: () => { if (admitted) { const resolve = admitted; admitted = null; resolve(); } return now; }, saveToken: async () => {} });
  const port = await server.listen(); t.after(() => server.close());
  const pair = code => fetch(`http://127.0.0.1:${port}/pair`, { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ code }) });
  async function slowRequest() {
    const arrival = new Promise(resolve => { admitted = resolve; });
    let resolve;
    const result = new Promise(done => { resolve = done; });
    const req = http.request({ hostname: '127.0.0.1', port, path: '/pair', method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json' } }, res => { res.resume(); res.on('end', () => resolve(res.statusCode)); });
    req.flushHeaders(); await arrival;
    return { finish: code => { req.end(JSON.stringify({ code })); return result; } };
  }
  const expired = server.createPairCode(); const first = await slowRequest(); now += 120001;
  assert.equal(await first.finish(expired.code), 403);
  const exhausted = server.createPairCode(); const second = await slowRequest();
  for (let i = 0; i < 5; i++) assert.equal((await pair('wrong')).status, 403);
  assert.equal(await second.finish(exhausted.code), 403);
  server.createPairCode(); const third = await slowRequest(); const replacement = server.createPairCode();
  assert.equal(await third.finish(replacement.code), 403);
  assert.equal((await pair(replacement.code)).status, 200);
});
